# Generated by Django 5.2.1 on 2026-05-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='icon',
            field=models.CharField(default='📍', max_length=30),
        ),
    ]
