# Generated by Django 5.2.1 on 2026-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_list_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
