# Generated by Django 5.2.1 on 2026-05-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_list_cover_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='external_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
    ]
