# Generated by Django 5.2.1 on 2026-05-26 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_listitem_external_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='shared_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
